[[library]]
type="git"
name="gd"
path="https://github.com/GodotNativeTools/godot-cpp"
postClone="git submodule update --init && sed -ie 's|json_api_file)|json_api_file); exit()|' SConstruct && scons generate_bindings=yes; mv include/core/* include/ && mv include/gen/* include/ && mv src/core/* ./ && mv src/gen/* ./ && mv godot_headers/* include/ && find . -name '*.?pp' -exec sed -i 's|^#include <core/|#include <|' {} \\;"
incdir="include"
includes=[
"AABB.hpp",
"Array.hpp",
"Basis.hpp",
"Color.hpp",
"CoreTypes.hpp",
"Defs.hpp",
"Dictionary.hpp",
"GodotGlobal.hpp",
"Godot.hpp",
"GodotProfiling.hpp",
"NodePath.hpp",
"Plane.hpp",
"PoolArrays.hpp",
"Quat.hpp",
"Rect2.hpp",
"Ref.hpp",
"RID.hpp",
"String.hpp",
"TagDB.hpp",
"Transform2D.hpp",
"Transform.hpp",
"Variant.hpp",
"Vector2.hpp",
"Vector3.hpp",
"Wrapped.hpp",
"AcceptDialog.hpp",
"AnimatedSprite3D.hpp",
"AnimatedSprite.hpp",
"AnimatedTexture.hpp",
"Animation.hpp",
"AnimationNodeAdd2.hpp",
"AnimationNodeAdd3.hpp",
"AnimationNodeAnimation.hpp",
"AnimationNodeBlend2.hpp",
"AnimationNodeBlend3.hpp",
"AnimationNodeBlendSpace1D.hpp",
"AnimationNodeBlendSpace2D.hpp",
"AnimationNodeBlendTree.hpp",
"AnimationNode.hpp",
"AnimationNodeOneShot.hpp",
"AnimationNodeOutput.hpp",
"AnimationNodeStateMachine.hpp",
"AnimationNodeStateMachinePlayback.hpp",
"AnimationNodeStateMachineTransition.hpp",
"AnimationNodeTimeScale.hpp",
"AnimationNodeTimeSeek.hpp",
"AnimationNodeTransition.hpp",
"AnimationPlayer.hpp",
"AnimationRootNode.hpp",
"AnimationTrackEditPlugin.hpp",
"AnimationTree.hpp",
"AnimationTreePlayer.hpp",
"Area2D.hpp",
"Area.hpp",
"ArrayMesh.hpp",
"ARVRAnchor.hpp",
"ARVRCamera.hpp",
"ARVRController.hpp",
"ARVRInterfaceGDNative.hpp",
"ARVRInterface.hpp",
"ARVROrigin.hpp",
"ARVRPositionalTracker.hpp",
"ARVRServer.hpp",
"AStar2D.hpp",
"AStar.hpp",
"AtlasTexture.hpp",
"AudioBusLayout.hpp",
"AudioEffectAmplify.hpp",
"AudioEffectBandLimitFilter.hpp",
"AudioEffectBandPassFilter.hpp",
"AudioEffectChorus.hpp",
"AudioEffectCompressor.hpp",
"AudioEffectDelay.hpp",
"AudioEffectDistortion.hpp",
"AudioEffectEQ10.hpp",
"AudioEffectEQ21.hpp",
"AudioEffectEQ6.hpp",
"AudioEffectEQ.hpp",
"AudioEffectFilter.hpp",
"AudioEffectHighPassFilter.hpp",
"AudioEffectHighShelfFilter.hpp",
"AudioEffect.hpp",
"AudioEffectInstance.hpp",
"AudioEffectLimiter.hpp",
"AudioEffectLowPassFilter.hpp",
"AudioEffectLowShelfFilter.hpp",
"AudioEffectNotchFilter.hpp",
"AudioEffectPanner.hpp",
"AudioEffectPhaser.hpp",
"AudioEffectPitchShift.hpp",
"AudioEffectRecord.hpp",
"AudioEffectReverb.hpp",
"AudioEffectSpectrumAnalyzer.hpp",
"AudioEffectSpectrumAnalyzerInstance.hpp",
"AudioEffectStereoEnhance.hpp",
"AudioServer.hpp",
"AudioStreamGenerator.hpp",
"AudioStreamGeneratorPlayback.hpp",
"AudioStream.hpp",
"AudioStreamMicrophone.hpp",
"AudioStreamOGGVorbis.hpp",
"AudioStreamPlayback.hpp",
"AudioStreamPlaybackResampled.hpp",
"AudioStreamPlayer2D.hpp",
"AudioStreamPlayer3D.hpp",
"AudioStreamPlayer.hpp",
"AudioStreamRandomPitch.hpp",
"AudioStreamSample.hpp",
"BackBufferCopy.hpp",
"BakedLightmapData.hpp",
"BakedLightmap.hpp",
"BaseButton.hpp",
"BitmapFont.hpp",
"BitMap.hpp",
"Bone2D.hpp",
"BoneAttachment.hpp",
"BoxContainer.hpp",
"BoxShape.hpp",
"BulletPhysicsDirectBodyState.hpp",
"BulletPhysicsServer.hpp",
"ButtonGroup.hpp",
"Button.hpp",
"Camera2D.hpp",
"CameraFeed.hpp",
"Camera.hpp",
"CameraServer.hpp",
"CameraTexture.hpp",
"CanvasItem.hpp",
"CanvasItemMaterial.hpp",
"CanvasLayer.hpp",
"CanvasModulate.hpp",
"CapsuleMesh.hpp",
"CapsuleShape2D.hpp",
"CapsuleShape.hpp",
"CenterContainer.hpp",
"CharFXTransform.hpp",
"CheckBox.hpp",
"CheckButton.hpp",
"CircleShape2D.hpp",
"ClassDB.hpp",
"ClippedCamera.hpp",
"CollisionObject2D.hpp",
"CollisionObject.hpp",
"CollisionPolygon2D.hpp",
"CollisionPolygon.hpp",
"CollisionShape2D.hpp",
"CollisionShape.hpp",
"ColorPickerButton.hpp",
"ColorPicker.hpp",
"ColorRect.hpp",
"ConcavePolygonShape2D.hpp",
"ConcavePolygonShape.hpp",
"ConeTwistJoint.hpp",
"ConfigFile.hpp",
"ConfirmationDialog.hpp",
"Container.hpp",
"Control.hpp",
"ConvexPolygonShape2D.hpp",
"ConvexPolygonShape.hpp",
"CPUParticles2D.hpp",
"CPUParticles.hpp",
"Crypto.hpp",
"CryptoKey.hpp",
"CSGBox.hpp",
"CSGCombiner.hpp",
"CSGCylinder.hpp",
"CSGMesh.hpp",
"CSGPolygon.hpp",
"CSGPrimitive.hpp",
"CSGShape.hpp",
"CSGSphere.hpp",
"CSGTorus.hpp",
"CubeMap.hpp",
"CubeMesh.hpp",
"Curve2D.hpp",
"Curve3D.hpp",
"Curve.hpp",
"CurveTexture.hpp",
"CylinderMesh.hpp",
"CylinderShape.hpp",
"DampedSpringJoint2D.hpp",
"DirectionalLight.hpp",
"Directory.hpp",
"DynamicFontData.hpp",
"DynamicFont.hpp",
"EditorExportPlugin.hpp",
"EditorFeatureProfile.hpp",
"EditorFileDialog.hpp",
"EditorFileSystemDirectory.hpp",
"EditorFileSystem.hpp",
"EditorImportPlugin.hpp",
"EditorInspector.hpp",
"EditorInspectorPlugin.hpp",
"EditorInterface.hpp",
"EditorNavigationMeshGenerator.hpp",
"EditorPlugin.hpp",
"EditorProperty.hpp",
"EditorResourceConversionPlugin.hpp",
"EditorResourcePreviewGenerator.hpp",
"EditorResourcePreview.hpp",
"EditorSceneImporterAssimp.hpp",
"EditorSceneImporter.hpp",
"EditorScenePostImport.hpp",
"EditorScript.hpp",
"EditorSelection.hpp",
"EditorSettings.hpp",
"EditorSpatialGizmo.hpp",
"EditorSpatialGizmoPlugin.hpp",
"EditorSpinSlider.hpp",
"EditorVCSInterface.hpp",
"EncodedObjectAsID.hpp",
"Engine.hpp",
"Environment.hpp",
"Expression.hpp",
"FileDialog.hpp",
"File.hpp",
"Font.hpp",
"FuncRef.hpp",
"GDNative.hpp",
"GDNativeLibrary.hpp",
"GDScriptFunctionState.hpp",
"GDScript.hpp",
"Generic6DOFJoint.hpp",
"Geometry.hpp",
"GeometryInstance.hpp",
"GIProbeData.hpp",
"GIProbe.hpp",
"GlobalConstants.hpp",
"Gradient.hpp",
"GradientTexture.hpp",
"GraphEdit.hpp",
"GraphNode.hpp",
"GridContainer.hpp",
"GridMap.hpp",
"GrooveJoint2D.hpp",
"HashingContext.hpp",
"HBoxContainer.hpp",
"HeightMapShape.hpp",
"HingeJoint.hpp",
"HScrollBar.hpp",
"HSeparator.hpp",
"HSlider.hpp",
"HSplitContainer.hpp",
"HTTPClient.hpp",
"HTTPRequest.hpp",
"__icalls.hpp",
"Image.hpp",
"ImageTexture.hpp",
"ImmediateGeometry.hpp",
"InputDefault.hpp",
"InputEventAction.hpp",
"InputEventGesture.hpp",
"InputEvent.hpp",
"InputEventJoypadButton.hpp",
"InputEventJoypadMotion.hpp",
"InputEventKey.hpp",
"InputEventMagnifyGesture.hpp",
"InputEventMIDI.hpp",
"InputEventMouseButton.hpp",
"InputEventMouse.hpp",
"InputEventMouseMotion.hpp",
"InputEventPanGesture.hpp",
"InputEventScreenDrag.hpp",
"InputEventScreenTouch.hpp",
"InputEventWithModifiers.hpp",
"Input.hpp",
"InputMap.hpp",
"InstancePlaceholder.hpp",
"InterpolatedCamera.hpp",
"IP.hpp",
"IP_Unix",
"ItemList.hpp",
"JavaClass.hpp",
"JavaClassWrapper.hpp",
"JavaScript.hpp",
"Joint2D.hpp",
"Joint.hpp",
"JSON.hpp",
"JSONParseResult.hpp",
"JSONRPC.hpp",
"KinematicBody2D.hpp",
"KinematicBody.hpp",
"KinematicCollision2D.hpp",
"KinematicCollision.hpp",
"Label.hpp",
"LargeTexture.hpp",
"Light2D.hpp",
"Light.hpp",
"LightOccluder2D.hpp",
"Line2D.hpp",
"LineEdit.hpp",
"LineShape2D.hpp",
"LinkButton.hpp",
"Listener.hpp",
"MainLoop.hpp",
"MarginContainer.hpp",
"Marshalls.hpp",
"Material.hpp",
"MenuButton.hpp",
"MeshDataTool.hpp",
"Mesh.hpp",
"MeshInstance2D.hpp",
"MeshInstance.hpp",
"MeshLibrary.hpp",
"MeshTexture.hpp",
"MobileVRInterface.hpp",
"MultiMesh.hpp",
"MultiMeshInstance2D.hpp",
"MultiMeshInstance.hpp",
"MultiplayerAPI.hpp",
"MultiplayerPeerGDNative.hpp",
"Mutex.hpp",
"NativeScript.hpp",
"Navigation2D.hpp",
"Navigation.hpp",
"NavigationMesh.hpp",
"NavigationMeshInstance.hpp",
"NavigationPolygon.hpp",
"NavigationPolygonInstance.hpp",
"NetworkedMultiplayerENet.hpp",
"NetworkedMultiplayerPeer.hpp",
"NinePatchRect.hpp",
"Node2D.hpp",
"Node.hpp",
"NoiseTexture.hpp",
"Object.hpp",
"OccluderPolygon2D.hpp",
"OmniLight.hpp",
"OpenSimplexNoise.hpp",
"OptionButton.hpp",
"OS.hpp",
"PackedDataContainer.hpp",
"PackedDataContainerRef.hpp",
"PackedScene.hpp",
"PacketPeerGDNative.hpp",
"PacketPeer.hpp",
"PacketPeerStream.hpp",
"PacketPeerUDP.hpp",
"PanelContainer.hpp",
"Panel.hpp",
"PanoramaSky.hpp",
"ParallaxBackground.hpp",
"ParallaxLayer.hpp",
"Particles2D.hpp",
"Particles.hpp",
"ParticlesMaterial.hpp",
"Path2D.hpp",
"PathFollow2D.hpp",
"PathFollow.hpp",
"Path.hpp",
"PCKPacker.hpp",
"Performance.hpp",
"PHashTranslation.hpp",
"PhysicalBone.hpp",
"Physics2DDirectBodyState.hpp",
"Physics2DDirectBodyStateSW.hpp",
"Physics2DDirectSpaceState.hpp",
"Physics2DServer.hpp",
"Physics2DServerSW.hpp",
"Physics2DShapeQueryParameters.hpp",
"Physics2DShapeQueryResult.hpp",
"Physics2DTestMotionResult.hpp",
"PhysicsBody2D.hpp",
"PhysicsBody.hpp",
"PhysicsDirectBodyState.hpp",
"PhysicsDirectSpaceState.hpp",
"PhysicsMaterial.hpp",
"PhysicsServer.hpp",
"PhysicsShapeQueryParameters.hpp",
"PhysicsShapeQueryResult.hpp",
"PinJoint2D.hpp",
"PinJoint.hpp",
"PlaneMesh.hpp",
"PlaneShape.hpp",
"PluginScript.hpp",
"PointMesh.hpp",
"Polygon2D.hpp",
"PolygonPathFinder.hpp",
"PopupDialog.hpp",
"Popup.hpp",
"PopupMenu.hpp",
"PopupPanel.hpp",
"Position2D.hpp",
"Position3D.hpp",
"PrimitiveMesh.hpp",
"PrismMesh.hpp",
"ProceduralSky.hpp",
"ProgressBar.hpp",
"ProjectSettings.hpp",
"ProximityGroup.hpp",
"ProxyTexture.hpp",
"QuadMesh.hpp",
"RandomNumberGenerator.hpp",
"Range.hpp",
"RayCast2D.hpp",
"RayCast.hpp",
"RayShape2D.hpp",
"RayShape.hpp",
"RectangleShape2D.hpp",
"Reference.hpp",
"ReferenceRect.hpp",
"ReflectionProbe.hpp",
"RegEx.hpp",
"RegExMatch.hpp",
"RemoteTransform2D.hpp",
"RemoteTransform.hpp",
"ResourceFormatLoaderCrypto.hpp",
"ResourceFormatLoader.hpp",
"ResourceFormatSaverCrypto.hpp",
"ResourceFormatSaver.hpp",
"Resource.hpp",
"ResourceImporter.hpp",
"ResourceInteractiveLoader.hpp",
"ResourceLoader.hpp",
"ResourcePreloader.hpp",
"ResourceSaver.hpp",
"RichTextEffect.hpp",
"RichTextLabel.hpp",
"RigidBody2D.hpp",
"RigidBody.hpp",
"RootMotionView.hpp",
"SceneState.hpp",
"SceneTree.hpp",
"SceneTreeTimer.hpp",
"ScriptCreateDialog.hpp",
"ScriptEditor.hpp",
"Script.hpp",
"ScrollBar.hpp",
"ScrollContainer.hpp",
"SegmentShape2D.hpp",
"Semaphore.hpp",
"Separator.hpp",
"Shader.hpp",
"ShaderMaterial.hpp",
"Shape2D.hpp",
"Shape.hpp",
"ShortCut.hpp",
"Skeleton2D.hpp",
"Skeleton.hpp",
"SkeletonIK.hpp",
"Skin.hpp",
"SkinReference.hpp",
"Sky.hpp",
"Slider.hpp",
"SliderJoint.hpp",
"SoftBody.hpp",
"SpatialGizmo.hpp",
"Spatial.hpp",
"SpatialMaterial.hpp",
"SpatialVelocityTracker.hpp",
"SphereMesh.hpp",
"SphereShape.hpp",
"SpinBox.hpp",
"SplitContainer.hpp",
"SpotLight.hpp",
"SpringArm.hpp",
"Sprite3D.hpp",
"SpriteBase3D.hpp",
"SpriteFrames.hpp",
"Sprite.hpp",
"StaticBody2D.hpp",
"StaticBody.hpp",
"StreamPeerBuffer.hpp",
"StreamPeerGDNative.hpp",
"StreamPeer.hpp",
"StreamPeerSSL.hpp",
"StreamPeerTCP.hpp",
"StreamTexture.hpp",
"StyleBoxEmpty.hpp",
"StyleBoxFlat.hpp",
"StyleBox.hpp",
"StyleBoxLine.hpp",
"StyleBoxTexture.hpp",
"SurfaceTool.hpp",
"TabContainer.hpp",
"Tabs.hpp",
"TCP_Server",
"TextEdit.hpp",
"TextFile.hpp",
"Texture3D.hpp",
"TextureArray.hpp",
"TextureButton.hpp",
"Texture.hpp",
"TextureLayered.hpp",
"TextureProgress.hpp",
"TextureRect.hpp",
"Theme.hpp",
"Thread.hpp",
"TileMap.hpp",
"TileSet.hpp",
"Timer.hpp",
"ToolButton.hpp",
"TouchScreenButton.hpp",
"Translation.hpp",
"TranslationServer.hpp",
"Tree.hpp",
"TreeItem.hpp",
"TriangleMesh.hpp",
"Tween.hpp",
"UndoRedo.hpp",
"UPNPDevice.hpp",
"UPNP.hpp",
"VBoxContainer.hpp",
"VehicleBody.hpp",
"VehicleWheel.hpp",
"VideoPlayer.hpp",
"VideoStreamGDNative.hpp",
"VideoStream.hpp",
"VideoStreamTheora.hpp",
"VideoStreamWebm.hpp",
"ViewportContainer.hpp",
"Viewport.hpp",
"ViewportTexture.hpp",
"VisibilityEnabler2D.hpp",
"VisibilityEnabler.hpp",
"VisibilityNotifier2D.hpp",
"VisibilityNotifier.hpp",
"VisualInstance.hpp",
"VisualScriptBasicTypeConstant.hpp",
"VisualScriptBuiltinFunc.hpp",
"VisualScriptClassConstant.hpp",
"VisualScriptComment.hpp",
"VisualScriptComposeArray.hpp",
"VisualScriptCondition.hpp",
"VisualScriptConstant.hpp",
"VisualScriptConstructor.hpp",
"VisualScriptCustomNode.hpp",
"VisualScriptDeconstruct.hpp",
"VisualScriptEditor.hpp",
"VisualScriptEmitSignal.hpp",
"VisualScriptEngineSingleton.hpp",
"VisualScriptExpression.hpp",
"VisualScriptFunctionCall.hpp",
"VisualScriptFunction.hpp",
"VisualScriptFunctionState.hpp",
"VisualScriptGlobalConstant.hpp",
"VisualScript.hpp",
"VisualScriptIndexGet.hpp",
"VisualScriptIndexSet.hpp",
"VisualScriptInputAction.hpp",
"VisualScriptIterator.hpp",
"VisualScriptLists.hpp",
"VisualScriptLocalVar.hpp",
"VisualScriptLocalVarSet.hpp",
"VisualScriptMathConstant.hpp",
"VisualScriptNode.hpp",
"VisualScriptOperator.hpp",
"VisualScriptPreload.hpp",
"VisualScriptPropertyGet.hpp",
"VisualScriptPropertySet.hpp",
"VisualScriptResourcePath.hpp",
"VisualScriptReturn.hpp",
"VisualScriptSceneNode.hpp",
"VisualScriptSceneTree.hpp",
"VisualScriptSelect.hpp",
"VisualScriptSelf.hpp",
"VisualScriptSequence.hpp",
"VisualScriptSubCall.hpp",
"VisualScriptSwitch.hpp",
"VisualScriptTypeCast.hpp",
"VisualScriptVariableGet.hpp",
"VisualScriptVariableSet.hpp",
"VisualScriptWhile.hpp",
"VisualScriptYield.hpp",
"VisualScriptYieldSignal.hpp",
"VisualServer.hpp",
"VisualShader.hpp",
"VisualShaderNodeBooleanConstant.hpp",
"VisualShaderNodeBooleanUniform.hpp",
"VisualShaderNodeColorConstant.hpp",
"VisualShaderNodeColorFunc.hpp",
"VisualShaderNodeColorOp.hpp",
"VisualShaderNodeColorUniform.hpp",
"VisualShaderNodeCompare.hpp",
"VisualShaderNodeCubeMap.hpp",
"VisualShaderNodeCubeMapUniform.hpp",
"VisualShaderNodeCustom.hpp",
"VisualShaderNodeDeterminant.hpp",
"VisualShaderNodeDotProduct.hpp",
"VisualShaderNodeExpression.hpp",
"VisualShaderNodeFaceForward.hpp",
"VisualShaderNodeFresnel.hpp",
"VisualShaderNodeGlobalExpression.hpp",
"VisualShaderNodeGroupBase.hpp",
"VisualShaderNode.hpp",
"VisualShaderNodeIf.hpp",
"VisualShaderNodeInput.hpp",
"VisualShaderNodeIs.hpp",
"VisualShaderNodeOuterProduct.hpp",
"VisualShaderNodeOutput.hpp",
"VisualShaderNodeScalarClamp.hpp",
"VisualShaderNodeScalarConstant.hpp",
"VisualShaderNodeScalarDerivativeFunc.hpp",
"VisualShaderNodeScalarFunc.hpp",
"VisualShaderNodeScalarInterp.hpp",
"VisualShaderNodeScalarOp.hpp",
"VisualShaderNodeScalarSmoothStep.hpp",
"VisualShaderNodeScalarSwitch.hpp",
"VisualShaderNodeScalarUniform.hpp",
"VisualShaderNodeSwitch.hpp",
"VisualShaderNodeTexture.hpp",
"VisualShaderNodeTextureUniform.hpp",
"VisualShaderNodeTextureUniformTriplanar.hpp",
"VisualShaderNodeTransformCompose.hpp",
"VisualShaderNodeTransformConstant.hpp",
"VisualShaderNodeTransformDecompose.hpp",
"VisualShaderNodeTransformFunc.hpp",
"VisualShaderNodeTransformMult.hpp",
"VisualShaderNodeTransformUniform.hpp",
"VisualShaderNodeTransformVecMult.hpp",
"VisualShaderNodeUniform.hpp",
"VisualShaderNodeVec3Constant.hpp",
"VisualShaderNodeVec3Uniform.hpp",
"VisualShaderNodeVectorClamp.hpp",
"VisualShaderNodeVectorCompose.hpp",
"VisualShaderNodeVectorDecompose.hpp",
"VisualShaderNodeVectorDerivativeFunc.hpp",
"VisualShaderNodeVectorDistance.hpp",
"VisualShaderNodeVectorFunc.hpp",
"VisualShaderNodeVectorInterp.hpp",
"VisualShaderNodeVectorLen.hpp",
"VisualShaderNodeVectorOp.hpp",
"VisualShaderNodeVectorRefract.hpp",
"VisualShaderNodeVectorScalarMix.hpp",
"VisualShaderNodeVectorScalarSmoothStep.hpp",
"VisualShaderNodeVectorScalarStep.hpp",
"VisualShaderNodeVectorSmoothStep.hpp",
"VScrollBar.hpp",
"VSeparator.hpp",
"VSlider.hpp",
"VSplitContainer.hpp",
"WeakRef.hpp",
"WebRTCDataChannelGDNative.hpp",
"WebRTCDataChannel.hpp",
"WebRTCMultiplayer.hpp",
"WebRTCPeerConnectionGDNative.hpp",
"WebRTCPeerConnection.hpp",
"WebSocketClient.hpp",
"WebSocketMultiplayerPeer.hpp",
"WebSocketPeer.hpp",
"WebSocketServer.hpp",
"WindowDialog.hpp",
"World2D.hpp",
"WorldEnvironment.hpp",
"World.hpp",
"X509Certificate.hpp",
"XMLParser.hpp",
"YSort.hpp",
]

[[library]]
type="file"
name="net"
path="../net"
includes=[
  "net/conn.hpp",
  "net/server.hpp",
  "net/rsa_key.hpp"
]

[[library]]
type="file"
name="sched"
path="../sched"
includes=[
  "sched/sched.hpp"
]

[[library]]
type="file"
name="ser"
path="../ser"
includes=[
  "ser/ser.hpp",
  "ser/proto.hpp"
]

[[library]]
type="file"
name="proto"
path="../proto"
includes=[
  "proto/proto.hpp"
]

[[library]]
type="file"
name="pi"
path="../pi"
includes=[
  "pi/pi.hpp"
]
